apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-monitor-ds
  labels:
    app: node-monitor
spec:
  selector:
    matchLabels:
      app: node-monitor
  template:
    metadata:
      labels:
        app: node-monitor
    spec:
      hostPID: true  # Acceso al PID del host
      hostNetwork: true  # Acceso a la red del host
      containers:
      - name: node-monitor
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100
          hostPort: 9100  # Expone en cada nodo
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "200m"